const { User } = require('../models');

// GET ALL USERS

// GET ONE USER BY ID

// POST A NEW USER

// PUT TO UPDATE A USER BY ITS ID

// DELETE TO REMOVE USER BY ITS ID


// POST TO ADD A NEW FRIEND TO USERS FRIEND LIST

// DELETE TO REMOVE FRIEND FROM USERS FRIEND LIST