// GET ALL THOUGHTS

// GET A SINGLE THOUGHT BY ITS _ID

// POST TO CREATE A NEW THOUGHT (DONT FORGET TO PUSH THE CREATED THOUGHTS _ID TO THE ASSOCIATED USERS THOUGHTS ARRAY FIELD)

// PUT TO UPDATE A THOUGHT BY ITS _ID

// DELETE TO REMOVE A THOUGHT BY ITS _ID

// REACTIONS

// POST TO CREATE A REACTION STORED IN A SINGLE THOUGHT'S REACTIONS ARRAY FIELD

// DELETE TO PULL AND REMOVE A REACTION BY THE REACTION'S REACTIONID VALUE