// GET ALL USERS

// GET A SINGLE USER BY ITS _ID AND POPULATED THOUGHT AND FRIEND DATA

// POST A NEW USER

// PUT TO UPDATE A USER BY ITS _ID

// DELETE TO REMOVE USER BY ITS _ID


// FRIENDS

// POST TO ADD NEW FRIEND TO A USER'S FRIEND LIST

// DELETE TO REMOVE A FRIEND FROM A USER'S FRIEND LIST