const { Schema, model } = require('mongoose');

// SCHEMA TO CREATE USER MODEL

// CREATE VIRTUAL PROPERTY CALLED friendCount THAT RETRIEVES THE LENGTH OF THE USERS friends ARRAY FIELD ON QUERY

// INITALIZE USER MODEL